version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - discovery.type=single-node
    ports: ['9200:9200']

#  terradex:
#    build: .
#    ports: ['8080:8080']
#    environment:
#      - TERRADEX_ELASTICSEARCH_HOST=http://elasticsearch:9200
#    depends_on: ['elasticsearch']

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on: ['elasticsearch']
    ports: ['5601:5601']
