########################################################################################################################
# Default Configuration for the Terradex Project

# All server specific configuration will go here
server:
  port: 8080

elasticsearch:
  host: http://localhost:9200
